module.exports =[{
  icon: 'cardboardfill',
  color: 'red',
  badge: 0,
  name: '创业'
}, {
  icon: 'recordfill',
  color: 'orange',
  badge: 0,
  name: '技术'
}, {
  icon: 'noticefill',
  color: 'olive',
  badge: 0,
  name: '母婴'
}, {
  icon: 'upstagefill',
  color: 'cyan',
  badge: 0,
  name: '美食'
}, {
  icon: 'discoverfill',
  color: 'purple',
  badge: 0,
  name: '娱乐'
}]